version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/azuredjango/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore(deps)"
